// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/control-panel/Hybrid.tsx": () => import("../components/mockups/control-panel/Hybrid.tsx"),
  "./components/mockups/control-panel/QuickPanel.tsx": () => import("../components/mockups/control-panel/QuickPanel.tsx"),
  "./components/mockups/control-panel/SidebarNav.tsx": () => import("../components/mockups/control-panel/SidebarNav.tsx"),
  "./components/mockups/control-panel/TopTabs.tsx": () => import("../components/mockups/control-panel/TopTabs.tsx")
};
